---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-example-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prometheus-example-app
  name: prometheus-example-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: ghcr.io/rhobs/prometheus-example-app:latest
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: prometheus-example-app
  name: prometheus-example-app-service
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus-example-app
  type: LoadBalancer
---
# kubectl create -f https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.74.0/bundle.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: prometheus-example-app
  labels:
    app.kubernetes.io/name: prometheus-example-app
  name: prometheus-example-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
  podMetricsEndpoints:
  - port: web
