---
apiVersion: v1
kind: Namespace
metadata:
  name: pi-logs
  labels:
    name: pi-logs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pi-logs
  name: pi-logs
  labels:
    app: pi-logs
spec:
  selector:
    matchLabels:
      app: pi-logs
  replicas: 2
  template:
    metadata:
      labels:
        app: pi-logs
    spec:
      containers:
      - name: pi-logs
        image: nickolivera296/prometheus-instrumentation:aa77765cd18b
        env:
          - name: ENCODE_HOST
            value: "pi-encode.pi.svc.cluster.local:8080"
          - name: DECODE_HOST
            value: "pi-decode.pi.svc.cluster.local:8080"
          - name: DB_HOST
            value: "pi-db.pi.svc.cluster.local:8080"
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pi-logs
  name: pi-logs
  namespace: pi-logs
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app: pi-logs
---
---
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: pi-logs
  namespace: pi-logs
spec:
  namespaceSelector:
    matchExpressions:
      - {key: "kubernetes.io/metadata.name", operator: In, values: ["pi-logs"]}

  selector:
    matchExpressions:
      - {key: "app", operator: In, values: ["pi-logs"]}

  relabelings:
  - action: replace
    sourceLabels:
    - __meta_kubernetes_namespace
    targetLabel: namespace