---
apiVersion: v1
kind: Namespace
metadata:
  name: pi-logs-custom3
  labels:
    name: pi-logs-custom3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pi-logs-custom3
  name: pi-logs-custom3
  labels:
    app: pi-logs-custom3
spec:
  selector:
    matchLabels:
      app: pi-logs-custom3
  replicas: 2
  template:
    metadata:
      labels:
        app: pi-logs-custom3
    spec:
      containers:
      - name: pi-logs-custom3
        image: nickolivera296/prometheus-instrumentation:7b13fb063908
        env:
          - name: ENCODE_HOST
            value: "pi-encode.pi.svc.cluster.local:8080"
          - name: DECODE_HOST
            value: "pi-decode.pi.svc.cluster.local:8080"
          - name: DB_HOST
            value: "pi-db.pi.svc.cluster.local:8080"
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pi-logs-custom3
  name: pi-logs-custom3
  namespace: pi-logs-custom3
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app: pi-logs-custom3
---
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: pi-logs-custom3
  namespace: pi-logs-custom3
spec:
  namespaceSelector:
    matchExpressions:
      - {key: "kubernetes.io/metadata.name", operator: In, values: ["pi-logs-custom3"]}

  selector:
    matchExpressions:
      - {key: "app", operator: In, values: ["pi-logs-custom3"]}

  relabelings:
  - action: replace
    sourceLabels:
    - __meta_kubernetes_namespace
    targetLabel: namespace
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: pi-logs-custom3
  labels:
    app.kubernetes.io/name: pi-logs-custom3
  name: pi-logs-custom3
spec:
  selector:
    matchExpressions:
      - {key: "app", operator: In, values: ["pi-logs-custom3"]}
  namespaceSelector:
    matchNames:
      - pi-logs-custom3
  podMetricsEndpoints:
    - port: web
