---
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: pi
  namespace: pi
spec:
  namespaceSelector:
    matchExpressions:
      - {key: "kubernetes.io/metadata.name", operator: In, values: ["pi"]}

  selector:
    matchExpressions:
      - {key: "app", operator: In, values: ["pi-decode","pi-encode","pi-frontend"]}

  relabelings:
  - action: replace
    sourceLabels:
    - __meta_kubernetes_namespace
    targetLabel: namespace
  - action: replace
    sourceLabels:
    - __meta_kubernetes_pod_node_name
    targetLabel: node
  - action: replace
    targetLabel: hardcodedlabel
    replacement: hardcodedvalue
---
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: pi-db
  namespace: pi
spec:
  namespaceSelector:
    matchExpressions:
      - {key: "kubernetes.io/metadata.name", operator: In, values: ["pi"]}

  selector:
    matchExpressions:
      - {key: "app", operator: In, values: ["pi-db"]}

  relabelings:
  - action: replace
    sourceLabels:
    - __meta_kubernetes_namespace
    targetLabel: namespace
  - action: replace
    sourceLabels:
    - __meta_kubernetes_pod_node_name
    targetLabel: node
  - action: replace
    targetLabel: hardcodedlabel
    replacement: hardcodedvalue