---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-load
  namespace: pi
data:
  conceal.sh: |-
    #!/bin/sh
    while true
        do
            N=$((1 + $RANDOM % 10))
            C=$((1 + $RANDOM % 3))
            S=$((1 + $RANDOM % 3))
            echo $N $C $S
            ab -n $N -c $C -l -d -S -q http://pi-frontend:8080/conceal
            sleep $S
        done
  show.sh: |-
    #!/bin/sh
    while true
        do
            N=$((1 + $RANDOM % 10))
            C=$((1 + $RANDOM % 3))
            S=$((1 + $RANDOM % 3))
            echo $N $C $S
            ab -n $N -c $C -l -d -S -q http://pi-frontend:8080/show
            sleep $S
        done
  logs.sh: |-
    #!/bin/sh
    while true
        do
            N=$((1 + $RANDOM % 17))
            C=$((1 + $RANDOM % 17))
            S=$((1 + $RANDOM % 3))
            echo $N $C $S
            ab -n $N -c $C -l -d -S -q http://pi-logs.pi-logs.svc.cluster.local:8080/logs
            # sleep $S
        done
  logs_custom.sh: |-
    #!/bin/sh
    while true
        do
            N=10
            C=10
            S=10
            echo $N $C $S
            ab -n $N -c $C -l -d -S -q http://pi-logs-custom3.pi-logs-custom3.svc.cluster.local:8080/static_log
            sleep $S
        done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pi
  name: pi-load
  labels:
    app: pi-load
spec:
  selector:
    matchLabels:
      app: pi-load
  replicas: 1
  template:
    metadata:
      labels:
        app: pi-load
    spec:
      containers:
        - name: pi-load
          image: alpine:latest
          command: ["/bin/sh"]
          args: ["-c", "apk add curl && apk add apache2-utils && apk add parallel && mkdir -p /root/.parallel && touch /root/.parallel/will-cite && parallel -j 4 /bin/sh ::: /etc/config/logs_custom.sh /etc/config/logs.sh /etc/config/show.sh /etc/config/conceal.sh"]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: pi-load
