---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
  labels:
    app: decode
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: decode
  replicas: 1
  template:
    metadata:
      labels:
        app: decode
    spec:
      containers:
      - name: decode
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: RELEASE
            value: {{ .Release.Name }}
          - name: SERVICE
            value: decode
          - name: TEMPO_HOST
            value: http://alloy.alloy.svc.cluster.local:4318/v1/traces
          - name: ENCODE_HOST
            value: encode.{{ .Values.namespace }}.svc.cluster.local:8080
          - name: DECODE_HOST
            value: decode.{{ .Values.namespace }}.svc.cluster.local:8080
          - name: DB_HOST
            value: db.{{ .Values.namespace }}.svc.cluster.local:8080
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: decode
  name: decode
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app: decode
