---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: db
  replicas: 2
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: RELEASE
            value: {{ .Release.Name }}
          - name: ENCODE_HOST
            value: encode.{{ .Values.namespace }}.svc.cluster.local:8080
          - name: DECODE_HOST
            value: decode.{{ .Values.namespace }}.svc.cluster.local:8080
          - name: DB_HOST
            value: db.{{ .Values.namespace }}.svc.cluster.local:8080
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app: db
