---
apiVersion: v1
kind: ConfigMap
metadata:
  name: load
  namespace: {{ .Values.namespace }}
data:
  conceal.sh: |-
    #!/bin/sh
    while true
        do
            N=$((1 + $RANDOM % 1))
            C=$((1 + $RANDOM % 1))
            S=$((60 + $RANDOM % 60))
            S=5
            echo $N $C $S
            ab -n $N -c $C -l -d -S -q http://frontend:8080/conceal
            sleep $S
        done
  show.sh: |-
    #!/bin/sh
    while true
        do
            N=$((1 + $RANDOM % 1))
            C=$((1 + $RANDOM % 1))
            S=$((1 + $RANDOM % 60))
            S=5
            echo $N $C $S
            ab -n $N -c $C -l -d -S -q http://frontend:8080/show
            sleep $S
        done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  labels:
    app: load
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: load
  replicas: 1
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
        - name: load-{{ .Release.Revision }}
          image: alpine:latest
          command: ["/bin/sh"]
          args: ["-c", "apk add curl && apk add apache2-utils && apk add parallel && mkdir -p /root/.parallel && touch /root/.parallel/will-cite && parallel -j 3 /bin/sh ::: /etc/config/show.sh /etc/config/conceal.sh"]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: load
